name: Build For Linux i386

on:
    workflow_dispatch:

jobs:
  linux:
   name: Linux-i386
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v3
     with:
          fetch-depth: 0
          submodules: recursive
   - run: |
           sudo apt update --fix-missing
           sudo apt install build-essential cmake make gcc-multilib g++-multilib gcc g++ -y
           mkdir compiled && cd compiled
           cmake ..
           make
   - name: Upload artifacts
     uses: actions/upload-artifact@v3
     with:
          name: linux-i386
          path: compiled/dlls/hl.so
