name: Build For Linux i386

on:
    workflow_dispatch:

jobs:
  linux:
   name: Linux-i386
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v3
     with:
          fetch-depth: 0
          submodules: recursive
   - run: |
           sudo apt update --fix-missing
           sudo apt install docker.io -y
           docker pull ubuntu:16.10-i386

   - name: Docker Work
     run: |
         docker run -it --rm \
          -v $PWD:/app \
          ubuntu:16.10-i386 \
          bash -c "apt update && apt install build-essential cmake make gcc g++ -y && mkdir compiled && cd compiled && cmake .. && make"

   - name: Upload artifacts
     uses: actions/upload-artifact@v3
     with:
          name: linux-i386
          path: compiled/
