name: Build For Linux i386

on:
    workflow_dispatch:

jobs:
  linux:
   name: Linux-i386
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v3
     with:
          fetch-depth: 0
          submodules: recursive
   - run: |
           sudo apt remove containerd -y
           sudo apt purge containerd.io -y
           sudo apt update
           sudo apt install docker.io -y
           docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
           docker build --build-arg BASE_IMAGE=32bit/buntu:16.04 -t 32bit/ubuntu:16.04 -f Dockerfile.i386 .
  
   - name: Docker Work
     run: |
         docker run -it --rm \
          -v $PWD:/app \
          32bit/ubuntu:16.04 \
          bash -c "apt update && apt install build-essential cmake make gcc g++ -y && mkdir compiled && cd compiled && cmake .. && make"

   - name: Upload artifacts
     uses: actions/upload-artifact@v3
     with:
          name: linux-i386
          path: compiled/
