name: Build for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        cmake_version: [3.13.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          choco install cmake --version ${{ matrix.cmake_version }} --yes

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
              build/dlls/Release/hl.dll
              build/cl_dll/Release/client.dll
