name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - icon: '⬛'
            sys: mingw32

    name: Build ${{ matrix.sys }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          install: >-
            git
            make
            cmake

      - name: Build project
        run: |
          cmake -G "MSYS Makefiles" -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build
