name: Windows Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSYS2
      uses: matken11235/setup-msys2@v2
      with:
        mingw: x86_64
        update: true

    - name: Install dependencies
      run: pacman -S --noconfirm cmake

    - name: Build
      run: cmake -B build && cmake --build build --config Release

    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: xash3d_windows_build
        path: build
