name: Build for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MinGW
      run: choco install mingw -y

    - name: Configure CMake
      run: cmake -G "MinGW Makefiles" .

    - name: Build
      run: cmake --build . --config Release

    - name: Install
      run: cmake --install build/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
          name: windows-build
          path: build
